application: govinspector
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /
  script: main.py

- url: /admin/add_issue
  script: add_issue.py

- url: /admin/set_secret
  script: set_secret.py

- url: /test
  script: model_test.py

